# Generated by Django 5.0.4 on 2024-04-18 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_airline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runway_number', models.IntegerField(default=0)),
                ('runway_designation', models.CharField(choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right'), ('N', 'None')], max_length=1)),
                ('length', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='core.airport')),
            ],
        ),
    ]
